### ISSUE TITLE
Add prominent highlight to active page/image

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/uv-en-GB-theme#4]
This should have been implemented in #2 (ref sul-dlss/content_search#33), but was overlooked. 

As-is, #2 removes the document highlight entirely. @ggeisler's mockups on sul-dlss/content_search#33 indicate that the document highlight should appear as follows:

![](https://user-images.githubusercontent.com/101482/34731868-d134d64c-f520-11e7-9d6f-6fefa0ad2040.png)

**Comment by camillevilla** [comment]
After discussion with @ggeisler yesterday, we decided that centering the page numbers should be pushed to later theming work because it's affected by hit counters. See:
<img width="217" alt="uv thumbnails with hits per page" src="https://user-images.githubusercontent.com/5402927/36039737-3ff00484-0d78-11e8-9e74-87e814a86dce.png">
